name: Create Azure Storage Account

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  create-storage-account:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: 'Login to Azure using OIDC'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Create Azure Storage Account
      run: |
        STORAGE_ACCOUNT_NAME="mystorage$RANDOM"
        az storage account create \
          --name $STORAGE_ACCOUNT_NAME \
          --resource-group CareerByteCode-RG \
          --location eastus \
          --sku Standard_LRS
        echo "Storage account $STORAGE_ACCOUNT_NAME created."
